import java.io.IOException;
import java.util.Base64;

public class Main {

    public final static String INPUT = "Ymx2eXN3eGlobG5kd2h6\n" +
            "ZWNmeXR2dnRydm9h\n" +
            "a2xkamtjbm9oamxkdnJhcWp4bg==\n" +
            "ZGRkY25pbHBldng=\n" +
            "c2hoa2ZsdGJqYmF3Z2Jm\n" +
            "cWFidHZhZXV2a2xkeXQ=\n" +
            "YXd6dnlla3o=\n" +
            "c3VrbXNrZGJqcWd0YXh4aHQ=\n" +
            "a2dpcXV3ZWN4Yw==\n" +
            "bmJ3dmE=\n" +
            "dHR4ZXdncWpoYWpyamJx\n" +
            "aWRxaWFhY3lwY3VjY2NpdmM=\n" +
            "a3ZxcA==\n" +
            "YmR4andtemR5cW1oeXduZQ==\n" +
            "a3JlYW14dGNwbnhoYnY=\n" +
            "aGF4cGtobXY=\n" +
            "bHlycXVoeGh0dXFwYQ==\n" +
            "bWFzZHhsa2xtbA==\n" +
            "eWducXp5Y2l6dm9rb2hhdA==\n" +
            "cGtiYXFweA==\n" +
            "cnFua3l2b2tt\n" +
            "aXNvcw==\n" +
            "Y2Rpc3Jub3NxaGY=\n" +
            "aXVldw==\n" +
            "enZ4bXVzbWFndG51cmFvemo=\n" +
            "cnBqaGl2dWR5b3JnZmlhdHRzdg==\n" +
            "c2d4\n" +
            "YmJvZHhldnRjaWZ3ZHhyeWR4YQ==\n" +
            "eW9xcGV3eXBoYW9vYQ==\n" +
            "cHd0cXJ4bHVwa3loanY=\n" +
            "bHRucXB1bmk=\n" +
            "d2k=\n" +
            "bmR4b3pqb25pZ21i\n" +
            "am53ZGtla2dmdmNwcHpodXFhcQ==\n" +
            "dmxu\n" +
            "b2E=\n" +
            "dHV0Z3FxZWd1aHQ=\n" +
            "dGo=\n" +
            "c2Flam5vc2x0dXpmZ29i\n" +
            "bGpoZHdpc2c=\n" +
            "cm1m\n" +
            "dm1ncnB3ZWdpdnJ0Zw==\n" +
            "aWJ1c3J4dXVvaHRxZnVyaWI=\n" +
            "bmt5bA==\n" +
            "dGJ1aXl2amJjdXN2cGppYmFsag==\n" +
            "cGN5Z3Jq\n" +
            "aHZzdHpjdWt3\n" +
            "a2xmd2dncGppZnNnaGxtZQ==\n" +
            "bWhzdXV6\n" +
            "aWZrcmR6bXB0dXZ1d3dr\n" +
            "dGRscmJrcnR2dWtidWNha2Y=\n" +
            "Z3pnZGdicHllaw==\n" +
            "cHVnYm5nZndweQ==\n" +
            "b2Rib2s=\n" +
            "d2poeWF3b3Rkbmdu\n" +
            "eGM=\n" +
            "dnN4c2VmenRxZWZiZWU=\n" +
            "b2tqZWN4bGRw\n" +
            "ZWNleHVsanVm\n" +
            "Y3F1bWxzc3Vw\n" +
            "c3FrbGpnanl6eXl5cmpzZQ==\n" +
            "bWlw\n" +
            "cXdiZHVndmpheWE=\n" +
            "bWdsc29jeHRjeHFsbGE=\n" +
            "bnJpcWNra2RkamNkYg==\n" +
            "Z2tw\n" +
            "ZnNpaHJ2\n" +
            "YWVraWdjZmh6dm5wbnd5\n" +
            "b2NuYnZkcmp5dXBhdQ==\n" +
            "Z28=\n" +
            "bWVk\n" +
            "bmdu\n" +
            "dHdz\n" +
            "cnl5ZGx1ZWhsYw==\n" +
            "cGFvcw==\n" +
            "ZGo=\n" +
            "Z2llb3V2\n" +
            "bWlt\n" +
            "c2V6\n" +
            "emJzcXJkc3Jxc3hmbg==\n" +
            "a3JtcQ==\n" +
            "eW56eQ==\n" +
            "YnNiemJjdWVp\n" +
            "Y2Vteg==\n" +
            "ZXFvdGZkb3o=\n" +
            "ZGw=\n" +
            "YWlvc3JmaHR0amRo\n" +
            "aWp1eWJsemU=\n" +
            "eHpmeA==\n" +
            "eGJudGRuYWc=\n" +
            "cG1mZHNwYWlwbXlhamN1\n" +
            "ZGplbHh0emZneXRxa2Z0Y2pxbw==\n" +
            "cmhtdmQ=\n" +
            "Z3l1aXVk\n" +
            "aXd6ZWxpcHhuamdxZWtv\n" +
            "eWpr\n" +
            "eGxseGR4amp0bmptY2NsdWc=\n" +
            "ZHFraA==\n" +
            "dmQ=\n" +
            "bXJseGxsaWhjZ2p1c2d6YmJqdA==\n" +
            "cXdkbG1xeGhoaXFy\n" +
            "dGRpZmly\n" +
            "ZHF6bQ==\n" +
            "enZ4aWlnZw==\n" +
            "dGtrc2N1dXNvcw==\n" +
            "d3hndHd1d2tra29hY2l0\n" +
            "Z3lteHB5b2ZjeWhqaXVydnJr\n" +
            "eXRla2pveGxtZWZj\n" +
            "cnpoYmdnd3NmdA==\n" +
            "bWdob3h4a3N1Ymdm\n" +
            "ZGhrcXVla3Btb25ucnJuag==\n" +
            "dXdhcnd4YmZkeGpy\n" +
            "Ym9ld2Frc2NrZnlsYmNv\n" +
            "d2NqYXp3ZHV2\n" +
            "bHZ3amV2d2dnZm5rbmY=\n" +
            "Y2dueW9hcmFhbA==\n" +
            "bXhw\n" +
            "b3F2\n" +
            "Y3h5aWZlZ3pkcWl5am1i\n" +
            "dXNrZWlqemJpaGpncnp5Znc=\n" +
            "aHlzcXB0amRqYg==\n" +
            "anlzcXJibWhsdGdqa3U=\n" +
            "dW1tdWZtbHh0bWNhZmtjdw==\n" +
            "anZma29paW53YW5udXBrdQ==\n" +
            "dXVvc3RrYW1jbWlsY2Q=\n" +
            "dnBwZHFrdXBuZ292\n" +
            "ZnJpb2RqdGRybXB4Z213cw==\n" +
            "a2lmc3ZsanF6dGN6ZGJ4Yw==\n" +
            "YWdheGVvY2R0b3VxZnE=\n" +
            "eWN1bWpkdmhnZm5hdnZoaWpvdA==\n" +
            "bW14cms=\n" +
            "eHh1YXlhY29seGdjdWI=\n" +
            "eXZyeHdhc3Bham1xbHlk\n" +
            "bGFjamlmcWd6eGJqZ2hudHRu\n" +
            "Z3l6aGxycGJsamRqa3ZvZGdxcw==\n" +
            "dHV6c2x0cGZwam1xaQ==\n" +
            "YWZnZnhzbGFwYXVy\n" +
            "cGdoZGdma2RlbHVsb2w=\n" +
            "aWlhZW56YmFhYXd2aWFxYXln\n" +
            "aW53ZmVs\n" +
            "dGtzZ3dtb2VuZGl6b3hvZ2Zh\n" +
            "Z2FpZWRmanZub3Njem51\n" +
            "d2ppZ3ZtbA==\n" +
            "YWx2bGZ0eGJyYnV6YmFseHR1\n" +
            "ZWRpZm1xeHhra2tkanZmcnVhdQ==\n" +
            "Y2J3\n" +
            "bHA=\n" +
            "ZGNua2NlYmFs\n" +
            "cHBneGU=\n" +
            "Z2k=\n" +
            "aWp0emFrcm95d2s=\n" +
            "emNkb2dvdGVn\n" +
            "YXBudml2bg==\n" +
            "Y2VwcmFsZGk=\n" +
            "Zm9n\n" +
            "eWtlZ3R2a2lmcmR6aWlueHk=\n" +
            "dWt1YW96Zmxubw==\n" +
            "eXFlam9hdQ==\n" +
            "cmlhZmd3a2l0\n" +
            "aHJ1emlucnNhYW4=\n" +
            "eWxmeWs=\n" +
            "am1md29xdQ==\n" +
            "c3J1\n" +
            "b2ZkcnZibG9ibXRsaw==\n" +
            "bWV3anU=\n" +
            "a2Rxb3N2dmZudm1naXJtaXA=\n" +
            "bm9zZHNycGFncXpqaHJnZ2U=\n" +
            "dW4=\n" +
            "anRqYXVoemZwcnI=\n" +
            "Y20=\n" +
            "cGlhb3A=\n" +
            "aWZheWJkcWJzZWF4cA==\n" +
            "Z2hqaXp5eHg=\n" +
            "bXN0\n" +
            "bnBlY3N0YmJldGliYno=\n" +
            "ZWdqdnV2amplaWdldW5vd3Br\n" +
            "YXlycHZhdGl4dm9xdw==\n" +
            "ZGN5aG1vcnR2dXZweGRxdm5yZg==\n" +
            "d3lwaHdzeG14d3l2c3htcQ==\n" +
            "cXZ0d2l2dHdpaXp0c2FlYXN0\n" +
            "bm5pYnpnbWZrcWh1a2tiZA==\n" +
            "YXRs\n" +
            "dGZ6anBhaHJhY3FieXdncXdh\n" +
            "Z2l3dGI=\n" +
            "cmRjcg==\n" +
            "eHhodGZmcXBwaHhleXl2\n" +
            "anFldXJp\n" +
            "dnVlbHRkbmxl\n" +
            "aG54a3BlZm5kZnZ2aG5kZmRzYg==\n" +
            "ZnhlcWpkbnJ2eHljbWJmbWk=\n" +
            "Z3lwbXk=\n" +
            "b293ZXp1cnJkbmFwamVp\n" +
            "ZW9saGRwbnl2cHN0ZHNxY3dubQ==\n" +
            "a2F5dg==\n" +
            "eXNicWtocGR6cW5hZg==\n" +
            "dnVvcHJ1ZWJv\n" +
            "eHdrd3djeXh3\n" +
            "dmxhaHFjdmJhbg==\n" +
            "dGU=\n" +
            "cGhtd3RodnFtZWo=\n" +
            "ZXVxZnRpeGlxdHJueXk=\n" +
            "dXV5anN4Z2lhcnJodGJ5bGtjZA==\n" +
            "emN2dGFmaXBl\n" +
            "cHF0bGdwamxtenZwcQ==\n" +
            "bmJza3Rkcg==\n" +
            "eXJvdG1hZGt0anhrYWFrYw==\n" +
            "b3M=\n" +
            "aGZ0ZnBiamhwZGJnZw==\n" +
            "bml4eGl2cA==\n" +
            "emtkYWp4cWppdHRnbWR5aA==\n" +
            "dGt3\n" +
            "aW1hdHJtemx5bnNv\n" +
            "dmFnamluanphdmRw\n" +
            "YW54cHI=\n" +
            "ZWxueWNvb2xp\n" +
            "dmNkcXFmcw==\n" +
            "bnF1a2FoaQ==\n" +
            "YWdwcmFmZnNpYnFpZnB5ZXBo\n" +
            "bHlj\n" +
            "YXljYm4=\n" +
            "a2VibGF6cGt2bmlvam9lZ3B6bw==\n" +
            "anJnZHFqdnVieGRlcW0=\n" +
            "bGprdXJ5Z2tr\n" +
            "eXJqYWZjcmVq\n" +
            "ZmVycQ==\n" +
            "a3Btc2FucmFoamZkbmI=\n" +
            "c3lt\n" +
            "eWlqb2VtdHRjeGdjZG9peWllYg==\n" +
            "amQ=\n" +
            "c2pmbml5dnNwbnpp\n" +
            "ZXdyZHFhbnp4Z3hicnR4a2Y=\n" +
            "bHNqbmltcWtoZGtmeXZy\n" +
            "aWlzc3VtbmVu\n" +
            "Y3ZsamViaHdybHplemN4enFn\n" +
            "a3k=\n" +
            "ZGh2bnZ4ZGV2YXM=\n" +
            "YXFnbXJqZ2hjc3F6eWZleg==\n" +
            "eWN0\n" +
            "b2dn\n" +
            "am1paHdpeGZ0eW9lbWNqZ3k=\n" +
            "cHllbXZjb3JycGdmcXZ3bQ==\n" +
            "eWN0cmhl\n" +
            "cWFkbHlhY2VlYWpwYWdteg==\n" +
            "dXhkcXBocWFsa3ZmeWlmeGF0\n" +
            "ZnRweG1mZW1sYXVyaWJidndxbg==\n" +
            "b21mYmRyZ2V5dHNxY2tyYg==\n" +
            "bHlscnp1b2Nkcg==\n" +
            "eXdweGNjYWtjcG1p\n" +
            "d2Zu\n" +
            "aXdzbmRpbmE=\n" +
            "dm5saHI=\n" +
            "bmZra3NmeWhocg==\n" +
            "Z2hncXBvY3k=\n" +
            "eXY=\n" +
            "emZxanVnZXpob3J6bGZkbGN0\n" +
            "bm96YWlwZmVpcA==\n" +
            "ZW10b3lla252\n" +
            "b3J5Y3Vqcw==\n" +
            "dGRnc3FpZWhxYnR6aHNvcw==\n" +
            "cW9vcHk=\n" +
            "dmtmdWlkcmd2dm5pcWVqdg==\n" +
            "bWtuZHlqZ29yemY=\n" +
            "dXhm\n" +
            "ZGxvdXJvdg==\n" +
            "dXJoYmlnZWd0YWV1\n" +
            "b3dzYWhjdGt4a3VhemhrdGY=\n" +
            "cGJ2bnA=\n" +
            "dGJlYnZ1YWlhaXphZnlu\n" +
            "ZnBrc3U=\n" +
            "Z3N2d2NpbXhkYXB4ZnRh\n" +
            "YmRtZHFtY3hp\n" +
            "emVkeGN3ZGE=\n" +
            "emFzeHhqZ3dxZ3l0d29s\n" +
            "ZHU=\n" +
            "c2J2c2x5\n" +
            "c21xbA==\n" +
            "bnRvem5ndnlnd2Fz\n" +
            "dGdsb2dxd2lwaXlidnNm\n" +
            "emlvdWtoZXVsbw==\n" +
            "dmh2eXl6eWNlZWhrbndpeGY=\n" +
            "bXVjcHJwYXJvaGNlZnFubWs=\n" +
            "cm9hcXdsZHJkdG9kYm5t\n" +
            "bHViaG56ZmNlbw==\n" +
            "cHlkbHV4ZHljbmhmc2R3eWxpbw==\n" +
            "enRjY2xqaGVnaGVz\n" +
            "Ync=\n" +
            "eHlxaHB0\n" +
            "eGhmeGN0eWJwand6dnE=\n" +
            "aWpo\n" +
            "cWNxZm9wdA==\n" +
            "eWNndno=\n" +
            "dHhpdGF5\n" +
            "amJqcw==\n" +
            "Z3hib3JkeGppandh\n" +
            "cHNoYnlz\n" +
            "dWpycHB6cmR0YXBjZQ==\n" +
            "Y3pjYmtncHBqemZhcWZrdWhy\n" +
            "d2t4emZ0Y3k=\n" +
            "YnJubmlwZXJnc2tq\n" +
            "bndwcG9paXhxZmx6amQ=\n" +
            "aml2amlzdGtzdGV3YmZ6cHVvbQ==\n" +
            "bmY=\n" +
            "eWp0YXZibHVtdWhi\n" +
            "eWF2Ynh6Y25iaHc=\n" +
            "cHp5b3V4ZnFqZHlyem5y\n" +
            "amZmc3l3ZWZu\n" +
            "amdjYQ==\n" +
            "YWN4cnluZ21vbGFpaml4dmJ2\n" +
            "c2Vo\n" +
            "d2pyY3JxbWttamRybml0cQ==\n" +
            "dnFmZ2NueGpmeWc=\n" +
            "YnZxcHA=\n" +
            "bHJ4YnBlZnBucnlqamZq\n" +
            "c3ptc3Bl\n" +
            "dHRxaWd3ZHF3ZnVrZQ==\n" +
            "dnZteXh0ZWJmbGNsZG5sYQ==\n" +
            "cXhhZnNka29z\n" +
            "cWdzeG5lanFxaHhseXBobnk=\n" +
            "dHJkbGtmY3VieWtoZ3diZ3Y=\n" +
            "YWhkcGpvb3NvdXZoaGd1bGxrcg==\n" +
            "Y2Zndg==\n" +
            "d3FhbGJ2am52bQ==\n" +
            "em15\n" +
            "bnRieXBmbGQ=\n" +
            "ZXd1ZW5oeQ==\n" +
            "Z20=\n" +
            "dWR6dGN2a2NhbWFubHd2eGlh\n" +
            "eGFqaXByYnBqZHJ5d3piag==\n" +
            "c2k=\n" +
            "dWZianl2b21tcWZkcm9zanJp\n" +
            "enVkbWZ4Y2NyeW0=\n" +
            "Ym5qeHZr\n" +
            "ZnBhZGZxcm5m\n" +
            "aXVlc21oaXltYWJpZWFubA==\n" +
            "bGtvbWFscnZ5YXB0eWs=\n" +
            "eG1lY3l2dHZncHF2dg==\n" +
            "dmZlYXJkb256cw==\n" +
            "ZXo=\n" +
            "cHA=\n" +
            "Z2thZG11cGZvZ3FvaWM=\n" +
            "cXRwdHNubnJvd2ppemh1YmVj\n" +
            "emJwYWtpc2Joenp0cHVodG1y\n" +
            "YWhqZG5lZA==\n" +
            "emFib3lobWllbXo=\n" +
            "a25hY213YnlienVyamlkc3d6\n" +
            "cGhwenp5ZHF5dm1heGZ2aA==\n" +
            "aHdyaWlq\n" +
            "bnZpZHR6bXZp\n" +
            "YmVlc3FueWh1cW11a3Jq\n" +
            "c2lyb2w=\n" +
            "bWpucnlnaA==\n" +
            "aGJpeXRhcG5lamdpbWQ=\n" +
            "bWR2YWVmeA==\n" +
            "cmFoZndrdHp0cGtvbA==\n" +
            "anR6c210bmNwc3VlZ3V1dQ==\n" +
            "ZG5jdWt1cGY=\n" +
            "cGh0cXVhdXA=\n" +
            "ZWt0bHpuamRjd292cnNxag==\n" +
            "aXJsb3hscXRsZ2NwbA==\n" +
            "bmhneGhp\n" +
            "cWR2a2to\n" +
            "ZnRiZmppa25zbg==\n" +
            "cWV3bHI=\n" +
            "bmR2a2J1\n" +
            "b3l4Zm93aXZyaHZ3aG4=\n" +
            "bmVnbHQ=\n" +
            "bHR1anFr\n" +
            "eHJjdXRt\n" +
            "dWJlbW1jZXd2\n" +
            "bHF1Z2Z6aw==\n" +
            "bWx2bnh0cG9td25vanZsYmx0\n" +
            "dnVy\n" +
            "ZXZjaWNna21ycXFjc3hoenc=\n" +
            "aG9ya3lyeXljZXc=\n" +
            "emdncmt6aXp5aHFr\n" +
            "b3Jv\n" +
            "dmVjeA==\n" +
            "a2FvZWp2bXJjYXVmYXU=\n" +
            "dmVtaHJz\n" +
            "YWVtcGpkbnA=\n" +
            "ZGd0YnhramxlenFv\n" +
            "ZmVrd2FybHVpemNk\n" +
            "YmFldWFsZmk=\n" +
            "aWJ4Z3BveHRta253em9tZGhm\n" +
            "a2hvaHphcWxlanJ4c2FoamI=\n" +
            "dWtveGd6ZWpnd3d2b3RzZHpscQ==\n" +
            "YWNlbXJ2bWVlem1pdnhxY2NjeQ==\n" +
            "cGE=\n" +
            "aG93a213\n" +
            "eWdmaHduYmxmamlpb2p1ZWZo\n" +
            "bXJxcHdrc3g=\n" +
            "b3E=\n" +
            "ZmxwbA==\n" +
            "eGdr\n" +
            "bXN6Z254YnhlaWRxd2o=\n" +
            "eGFoeGc=\n" +
            "cHZyeG5naG5wamNseGY=\n" +
            "aWdkbXBzdmVxcHZ0Y2R0\n" +
            "bW1nb21pdXZ1cm9ibGFsZmg=\n" +
            "cmVvbG53bXJkZXk=\n" +
            "ZmdtdmJ1YW53ZW51bg==\n" +
            "cXllZ29kZ3pkbGR3a3RncnB2\n" +
            "aWVqaWJmZWc=\n" +
            "YnB4b2hxZXBzbw==\n" +
            "bG1tdm1saXB5a3J6cA==\n" +
            "ZXllaWVydHhyd3FrbWd4aWNwZg==\n" +
            "Y2dzcXlp\n" +
            "emVi\n" +
            "b25jYnhqaXBpaXpl\n" +
            "b2J1YmlpdnlyeXpv\n" +
            "amludGJqdWE=\n" +
            "dm95enRzYWVqd2Rjcnc=\n" +
            "dHFsdGljbw==\n" +
            "eWVmdnBlcXFwb2R3bXk=\n" +
            "bWV4YXN2Y25rY3k=\n" +
            "ZXl2ZHg=\n" +
            "ZHdla2pocw==\n" +
            "dG5u\n" +
            "dHdqcnFlYnNt\n" +
            "dXh3d2N5cXlncnZoZGh4\n" +
            "dXd5aW1wa3FyYWU=\n" +
            "dWRwZW9kdmo=\n" +
            "Ymhod3h0Zg==\n" +
            "enhpZw==\n" +
            "cXR4dmNmYg==\n" +
            "ZXN3c2p1ZA==\n" +
            "b2pjamFx\n" +
            "bnRz\n" +
            "bmNo\n" +
            "bWhl\n" +
            "cHFiaWFha3Z5bGlsY2pv\n" +
            "enNzY2Rz\n" +
            "d3ZxcXF5bGl0cWN5eWh5dGhv\n" +
            "dHF6aHlhbWZsaGRycXpl\n" +
            "cHRobXBxaW5x\n" +
            "Y2drdWh2b251emJ2\n" +
            "cHZidWF0cXJneHF2cXY=\n" +
            "bG5qcXJ3dmo=\n" +
            "a2d4cGx3c3R1dHBnYmVieGc=\n" +
            "cHNobXVsbQ==\n" +
            "dmxyeGpoaHptaHRp\n" +
            "dm90ZnZubGxxdGxqdw==\n" +
            "cWdsb2tjb2F0\n" +
            "dWthc3Z6YWxhc2tmaGxrZXE=\n" +
            "d2J2dW9l\n" +
            "ZXpyaGd0cHZhaml2eXZh\n" +
            "c2JvaXRsZQ==\n" +
            "emw=\n" +
            "ZWhmamNnZHhoeHFobnppZ2hr\n" +
            "am1ncGh3d2RoempybWdj\n" +
            "dWpwaHhpb3dqa2Y=\n" +
            "dGd1bGhqbXpt\n" +
            "ZG9sc3R4bWdxZ25xYXZkdWVocg==\n" +
            "dmpzeGJr\n" +
            "YmRwZ2hudXhweW1uaHR2YWRq\n" +
            "YmhqbWdsY2Y=\n" +
            "eGxwamxwdGx3aW95dXJkdHFz\n" +
            "bGhtYWxjZm9uZHVldmVmenJhbA==\n" +
            "bGNsZGR5\n" +
            "c2w=\n" +
            "a3VmYWh5cGd2cXVicQ==\n" +
            "ZnNqZWlpa3lldXNsbGFkcWM=\n" +
            "cW1pcm5o\n" +
            "YmJ2cWZqbWx0cGdkbmtu\n" +
            "d3Q=\n" +
            "cW1xd3BoYm53cm50ZXNzcGxj\n" +
            "YWI=\n" +
            "YnhuYWNxcnJtcWRpdmk=\n" +
            "amlnc3p4Znh6cHd6bmV4cW9kaw==\n" +
            "c21pbG1xaWZkbWR6eGpx\n" +
            "dGZiZGlwcXVxeGxs\n" +
            "ZmZldWVnY29ha3Rtem1tZnBv\n" +
            "cHd2d2Fkd2t1dmZ5a3FtY2p2\n" +
            "bHRiaWpnenJiZGRybHlqanA=\n" +
            "dXV6aGlsdnBzeXhmdG5wdg==\n" +
            "a3BhZA==\n" +
            "anRrcmRka3Nucmx1dnVwdg==\n" +
            "c2ZkZG1lYml1dWlwZXloY2lq\n" +
            "eWFsanJ4dHhremtmeXpkc29u\n" +
            "aWxpY2Rlb24=\n" +
            "eWZlcg==\n" +
            "cmdub3B1eg==\n" +
            "eGxhd2p0emd0aGhsc3NnbWk=\n" +
            "Y2J3ZW5ncG0=\n" +
            "dHRwZXRs\n" +
            "Z251cHZlYndpY2dmcGZkcHVo\n" +
            "Z2x2dXZm\n" +
            "bXVkdQ==\n" +
            "YXduaWZ1bGlkcml4amphYw==\n" +
            "emx3em9uamlyY3ppbA==\n" +
            "Z2d0ZXBuaw==\n" +
            "bm4=\n" +
            "YmVyeQ==\n" +
            "eW5vYXBlZA==\n" +
            "eGx4ZQ==\n" +
            "aHFtaW12cGdydmJlaHRlag==\n" +
            "cXV0aQ==\n" +
            "cW1jc2t0am55am1pc2t6cXhxZw==\n" +
            "aWhlYWh4YWRocWdlaHliaA==\n" +
            "am1rc3pyeG5kYmFvdXphbA==\n" +
            "b2Nm\n" +
            "cm5vdGJrem52aWV3aHJ5\n" +
            "enp2b2x5YXdldXFzdHJyYWNl\n" +
            "cXVwaXM=\n" +
            "d2ZzdHFraWtkemJtdm96Yg==\n" +
            "eGd4anhlaWJuaA==\n" +
            "bG9pbHFzb3RyeWJqaGd2eXRo\n" +
            "bWFydWdwcHBkdGtiaG9kYg==\n" +
            "amxyYWNjZWtqaWo=\n" +
            "eHlibmxseWdmb21zbWZ1bXBhag==\n" +
            "YWdq\n" +
            "enVj\n" +
            "Y3pla3dsaWFh\n" +
            "aWJ1bQ==\n" +
            "ZHBjbWhzYWlwd2V2dA==\n" +
            "a216eWpncm1mdXRjd3RibW9ydA==\n" +
            "a2RvYXB5cXliZGhsc2N5\n" +
            "Z3Q=\n" +
            "dGh4b3pqd3Bz\n" +
            "bHNzY3ZpaWV6bmt6cQ==\n" +
            "cGllZ2lpZHR1amRlcnQ=\n" +
            "cWRueGlld2dzZXpveGRuemF5ZQ==\n" +
            "aXp5cmt1Z2Jz\n" +
            "b3Fxdw==\n" +
            "emF5ZXBkZmlpeGtwa3U=\n" +
            "YmxldXRla3Rxdnp2b3hobGw=\n" +
            "aXlpYmVtZnZhcnlsYWV6\n" +
            "c3preW5hcGduaXc=\n" +
            "bWZnY3drdmJpaG4=\n" +
            "Ymdwd3lkaGlveGxq\n" +
            "Z2Vhb2o=\n" +
            "ZW1tYWdnbQ==\n" +
            "d3BnaGR1dWthenk=\n" +
            "cG14bnBuZGdpcGw=\n" +
            "enFxcHU=\n" +
            "YnhxcmVnZGV3bGhzc2p1dmFr\n" +
            "Z2xiZHN0Z2xoY2xx\n" +
            "ZXRsbG5jdHlheXo=\n" +
            "ZnI=\n" +
            "YnJxaWNtbG5hamo=\n" +
            "ZWJ3ZXFsdmd1eHdta2NraA==\n" +
            "and5bmdpaml2bml2dHlzaGho\n" +
            "eG5l\n" +
            "bnFudXF0b3hyYmJrZHJ3c3lr\n" +
            "c3Zxb2Z3cg==\n" +
            "d2V4cHprbHJkZnM=\n" +
            "bnVwZmZmcGE=\n" +
            "YWRhZ3pyeXV6bHNhZg==\n" +
            "Y2ZlZWh3ZXN6bm1zeGk=\n" +
            "cHJ1eHhld2Zk\n" +
            "Y3hmemdvcHdoZ2xxYXJpenQ=\n" +
            "ZmhsZHpuc3liY3BpZA==\n" +
            "cGJlY2VzcXg=\n" +
            "a2VqcnVuYmY=\n" +
            "eXA=\n" +
            "YmpoY2dnanFjeWF3b2tm\n" +
            "anRnZ2d2cW11aXZuZ2V1aXZo\n" +
            "cXVpeA==\n" +
            "cnR2b3ltYnlkZ2tmd25j\n" +
            "enJr\n" +
            "aG93ZXVhZXJncw==\n" +
            "dnA=\n" +
            "aHF1bWtqcXduandycmZmdA==\n" +
            "cHRvdmFoY2N3bGh3eWg=\n" +
            "b3Rm\n" +
            "b2ZyemJnbGhqeg==\n" +
            "d3F0emxpeGt4aG1pYQ==\n" +
            "c3Js\n" +
            "cGZmaGppeA==\n" +
            "Y3FjcWNhc2U=\n" +
            "emtwcXF0\n" +
            "cnNseXFvbXpnZGxzcGtvY3dh\n" +
            "aHJ4dnNzeGk=\n" +
            "aHVzd3c=\n" +
            "Z2VtemNxcGV0\n" +
            "dWdvdnZid3M=\n" +
            "c2hrbHR3ZXk=\n" +
            "aGV1dHBob3FhZXBlaGY=\n" +
            "Zmxja3JtZw==\n" +
            "eXNweW12bXY=\n" +
            "enl5cXJ5aA==\n" +
            "YnJsc3dqag==\n" +
            "emJ1cw==\n" +
            "ZGlodnJ4eWdiZnY=\n" +
            "eGJvcHZtb21sbnZsZg==\n" +
            "cWw=\n" +
            "a3JtdmR1dWd0dw==\n" +
            "eWtid3Rsa3dubHRyaHZt\n" +
            "cGxjenNjZW55bWJieGtqcQ==\n" +
            "aGtwbA==\n" +
            "dm4=\n" +
            "b3FrcWphaHlsaA==\n" +
            "dHB1bmY=\n" +
            "amFjaGts\n" +
            "eWZuem9lYW9rbmNucmQ=\n" +
            "amVmdm13YnQ=\n" +
            "cW11cmFuYWxnYWNydnllYnN5\n" +
            "eXVoZw==\n" +
            "bGd2d2Rv\n" +
            "dmlvbnZic29hc250ZXR5d2c=\n" +
            "aHBmeXl3Zw==\n" +
            "bm13c3F2Zg==\n" +
            "dmltdmZub2N3cg==\n" +
            "bWtk\n" +
            "bGFnYXFseXd1ZnZ1Z2Z2a2d4cQ==\n" +
            "ZXBndg==\n" +
            "dHR5ZWxueHdjZms=\n" +
            "bWRuenVwcXI=\n" +
            "aWw=\n" +
            "eXl6aHZqY3ZreW95ZWZxc3ln\n" +
            "YWNkaGR5YnFyc2p6eA==\n" +
            "YWxsY2NpcmJydXpm\n" +
            "ZXNnZHJwYXJnaWJsY3pqc2c=\n" +
            "cng=\n" +
            "c2V3bw==\n" +
            "Y2x0aWlxY3Z4b2Rqa25maGg=\n" +
            "bmp5cGF6eWJoam9icHE=\n" +
            "bnpramFxbnh4cWZnZWs=\n" +
            "eHo=\n" +
            "bHFzd2dva2g=\n" +
            "ZnFhbHNocA==\n" +
            "Z3Vod3l4ZmVrdmdka3d2eHJv\n" +
            "Z2NpYXNxb2VkeHZtdGVlYng=\n" +
            "emo=\n" +
            "cXp2cndibm5oY3I=\n" +
            "ZHRkbw==\n" +
            "ZnZlc2Vncm12bmpqZnd3eg==\n" +
            "aHE=\n" +
            "amhzY3g=\n" +
            "ZmxkbWhreQ==\n" +
            "emVvaGJuZHVvbGVsa2x6dWR6bg==\n" +
            "dHN6YWh6\n" +
            "bGN0a3ZxdGhmeXNsYXg=\n" +
            "eWV1c3Vod251YmNyZnh2ag==\n" +
            "aG12dWdscGZpa2t1Yg==\n" +
            "eGVwbW1tdWNucHBhZg==\n" +
            "dmphZ2ViemZi\n" +
            "cmZ1ZG12ZG5wcGNwemF2\n" +
            "aGJ1eG51ZmJoaHdzdHZwZHM=\n" +
            "Z3pmb3VhdXVsYXl1Ym5idXl5bQ==\n" +
            "cWVrYWFtb3J0\n" +
            "Y29kdnF0YWVxdmU=\n" +
            "cXF0Z2xlbmFw\n" +
            "anVpcWxka3lnc3R4a29rbXZ5\n" +
            "bGxveWNs\n" +
            "cWZvaWtoY2I=\n" +
            "eWl3Z2Rl\n" +
            "amJpYXNwdWxwd3dzc2N2\n" +
            "c3U=\n" +
            "Z3RoY2NxbA==\n" +
            "cGp2cQ==\n" +
            "Y2JvZnV3aQ==\n" +
            "aWR2aWx5aHI=\n" +
            "ZHdsdGtoYnRndmNneXd0d2pheg==\n" +
            "d3RqanZh\n" +
            "d3p3aWFsYm95aGpoa2c=\n" +
            "a3NiaHF0eHdqYXBoa253dnU=\n" +
            "bHBsYg==\n" +
            "YnhzemJob3NxcHpreA==\n" +
            "eWppeW14c2ludnJ2b2c=\n" +
            "YWNmdXBkdGZxcW5vY2xkd3o=\n" +
            "enBwag==\n" +
            "dGZuZXFj\n" +
            "dGhhaGY=\n" +
            "eGJld293Yg==\n" +
            "OTA0\n" +
            "Y2xib3RzdGlodmJk\n" +
            "ZnBwdmdnbGRrdA==\n" +
            "bXBjeGRxZGpsdmZyY2JkdWN4cA==\n" +
            "cHhtcHA=\n" +
            "eGVjbnN1aXJpbHlmdmJuend5\n" +
            "b2lyeGFqemJibXBlbnI=\n" +
            "ZWhhbw==\n" +
            "d2Y=\n" +
            "cHZ6emV1bGZ1cmNnaXM=\n" +
            "anB2cmR0emZ0dGR4amly\n" +
            "cmpjZHppbmZ1Y3c=\n" +
            "Ympud2x4bmNsdGZoZmo=\n" +
            "bnFpd3BjZ2lnYmM=\n" +
            "cGptbnNuY3lxcA==\n" +
            "amRwd3RrYmV1bnZ0dmF0bW5y\n" +
            "b2x0YXNyaGN0cG1hcWxqcA==\n" +
            "cW5lemVsYWRscXNkbnF2dQ==\n" +
            "anlmag==\n" +
            "emF0dm4=\n" +
            "d2l0d2pj\n" +
            "dnJjc3Zra3dxYw==\n" +
            "Z2Z2cHdzb3Z2ZXNmbW54Y2M=\n" +
            "Z21hbXZyc3g=\n" +
            "eGl2dQ==\n" +
            "b2xmcXZlZ2N4cHBsdmI=\n" +
            "eGdl\n" +
            "ZGN0YWZoY3Bidm9ycG4=\n" +
            "bG1semZ4eXBvdGQ=\n" +
            "Z3lyZGhwdXE=\n" +
            "eW9ycnRndnlseWd2YWRidWw=\n" +
            "ZXBhbG5nY3FicHJnbHBmcw==\n" +
            "Zm5kcGRweWp1d2xpYQ==\n" +
            "b2lob2FvcHk=\n" +
            "cHB2ZHZqb3lrdGphc3o=\n" +
            "dm14bmZkbG5hZmZ6cnFtb3Y=\n" +
            "cnhrZ29neHRrdHE=\n" +
            "ZXRu\n" +
            "ZXp0YXVzZm9zbw==\n" +
            "a3FtaGdlaGo=\n" +
            "bnNlbnJ4eXJ1eG1xZXhj\n" +
            "anBwcmRk\n" +
            "dHNqZ29jbmV4amtsZWRlY3Rvcw==\n" +
            "eGt3\n" +
            "Y2ZxaQ==\n" +
            "enNs\n" +
            "ZHV6YWZ3Z2VxcWdwZnpqdGd4Yg==\n" +
            "Y3BsaHBrbg==\n" +
            "eHhxeA==\n" +
            "amxkdnpzb3Z0dnBuemRyenlj\n" +
            "dmVrZWRhcXB4Z3dwbXpq\n" +
            "aWx0aHdjb2d1\n" +
            "Z3Zicmd5aGdjb3JjanZ6c3Jw\n" +
            "a2xuY2dzbWFrenp2aQ==\n" +
            "eXpjb2Z3aQ==\n" +
            "cnRmdnhqcHBucGRteWh6b2Y=\n" +
            "ZHZseHI=\n" +
            "Y25lZGN4dw==\n" +
            "cW1oemhmYm9l\n" +
            "Y2x5eHdzanJqZQ==\n" +
            "dXlmbXl6aWxna3Nq\n" +
            "cnluY2dxd3V3eGptcWxvd2d5\n" +
            "cXd4cWRyag==\n" +
            "Y3Brb2k=\n" +
            "cXM=\n" +
            "dG90\n" +
            "cmdzenc=\n" +
            "cW8=\n" +
            "bWt3Y2E=\n" +
            "ZXp3amxpcG95\n" +
            "c2ZpZGZy\n" +
            "bnBiaXBjbmtyaHJleXlubg==\n" +
            "aHprd2VxaW90anpvbWlldg==\n" +
            "Ymg=\n" +
            "eWlxaGpzaXdwZm9x\n" +
            "d2F5amhyc3k=\n" +
            "cm5mYWpqYXlibGhiYm53YWRueA==\n" +
            "a3Nw\n" +
            "bHppbXpkZGQ=\n" +
            "dXd0ZHFlb3VjeXZ0eXk=\n" +
            "bWJnZ2RiaGk=\n" +
            "a2I=\n" +
            "dXR4dHRkYXBzbGJweno=\n" +
            "b2h6d2N2eG1rYmFyZXNhdnU=\n" +
            "YWNxcHZvd2Zl\n" +
            "aHRvdm8=\n" +
            "cnZ0dHRwaw==\n" +
            "bWRjaW5id3BmdmZr\n" +
            "cXhod2phdWpk\n" +
            "eXp0YXdzbndtbGxhdGk=\n" +
            "enljanptc3Jt\n" +
            "bGxteXQ=\n" +
            "cGR4eXE=\n" +
            "eGJmZXB4bg==\n" +
            "c2xtZw==\n" +
            "am54d2h3\n" +
            "YXI=\n" +
            "bHR5emh5eGNt\n" +
            "aGZ1ZXR1YWR4ZnV3dmhnZ2J3\n" +
            "c3Fkd2V0d3RqcXBhZ2tldg==\n" +
            "bGl2bWthbWFqa3c=\n" +
            "a3NzZmZmd2Rqb3Q=\n" +
            "YnhraGl3cGtqZHZnZ28=\n" +
            "eG1xeHF1dWhvcQ==\n" +
            "Z3Rmd2hjc3BuYnhiaXo=\n" +
            "a250YXhkY295Z3B6\n" +
            "cmhhY2hqbWhj\n" +
            "ZWljeWx1aXB5bHR2ank=\n" +
            "ZWxod2lqYml5dW9kaGU=\n" +
            "cGptcHVxbQ==\n" +
            "cmJy\n" +
            "d2t0bWNq\n" +
            "Y3J3\n" +
            "d25lZmZ5Yml4YW10\n" +
            "dXF3ZnJsYnVqbHpp\n" +
            "Y2RkaHRpcmo=\n" +
            "YmpydG4=\n" +
            "eWxteHdrc2xucmhjZQ==\n" +
            "Y3B5cXp0eWRwZGh2cQ==\n" +
            "emV6d29qdmxwdnd4\n" +
            "eGtjc2Zha21seQ==\n" +
            "cnN2bXp3cXVzY2tkaGx6b3Nmdg==\n" +
            "dm1z\n" +
            "Z2FtcHRwZnBxdm12dHZ0Zg==\n" +
            "dnZvYXd0Y21tZmlxc2E=\n" +
            "dGhqdHBiYXNw\n" +
            "d2hpdmd2Y3Rycw==\n" +
            "aHJ2ZmRtaWhpdGJu\n" +
            "cXNr\n" +
            "cmZ0bw==\n" +
            "amxw\n" +
            "b3l0\n" +
            "bG9vdnltb3o=\n" +
            "cXh4eWNtaGx3bXI=\n" +
            "YXZkY3lkcw==\n" +
            "a3Rhc29ld3djaHV4anVsd2Fu\n" +
            "Y25pd3JrY2ludWs=\n" +
            "bnJianJzaHp2aGQ=\n" +
            "a2ZhaXBobmlwdXVvZmp2Z3E=\n" +
            "bGtmZnJubmV5dWFoem1ycWJzYw==\n" +
            "Z2lkdmJ5dGZo\n" +
            "dnZ1eWxx\n" +
            "dWlycHJxZnJqeXJ6aA==\n" +
            "Y2JzcmZsc3px\n" +
            "ZG1hcWpuenZiZHFscXl3am1o\n" +
            "bWJobnp6emVtYWdqbHh2ZW4=\n" +
            "ZWt4aGZ6eWttYnZ1dm9sd2U=\n" +
            "eHVvaXdrbWk=\n" +
            "cG9xenpvY2dyc24=\n" +
            "aWZxZHQ=\n" +
            "ZnJtamNzdw==\n" +
            "a3J1\n" +
            "bnJw\n" +
            "bGJ6cnJ5em1tZmtj\n" +
            "cWJrYmQ=\n" +
            "YmNqb29oem9lbmR2\n" +
            "cGJxa2FteGFqdW1vd3RidW0=\n" +
            "cHNhbGJ2ZA==\n" +
            "cXNpZG4=\n" +
            "d3VranBocmtx\n" +
            "cnlvbg==\n" +
            "dXRnZm5q\n" +
            "enhyYnJteg==\n" +
            "c2JyZG9jZHFmaQ==\n" +
            "dGNscHRwaQ==\n" +
            "bXhvcHl4dXBjZ2VqZnc=\n" +
            "bHh0c2Jvdw==\n" +
            "aWp2enJteXBoY2tyem1zbXFv\n" +
            "dXhvY3pmdmZ0aHBucnp3bmg=\n" +
            "b291cHRuY3Zseg==\n" +
            "Zmducms=\n" +
            "YmQ=\n" +
            "bm96aG9pcG5mb2J0bWtuaA==\n" +
            "eGhubmg=\n" +
            "aHNncnFkbXhqaXZ4aGViZmV6\n" +
            "a2dxb2x2bXpkZw==\n" +
            "Zm1u\n" +
            "dGx4emE=\n" +
            "dXdzbWQ=\n" +
            "Z2U=\n" +
            "ZWxoZ2FobHpla25y\n" +
            "b2lncnphdHY=\n" +
            "aGNvaGxmYQ==\n" +
            "Z2NsZ3Rndnh0eA==\n" +
            "d2pzbW1rbW5mdHJtdXA=\n" +
            "Y255cGh2d2FieXNk\n" +
            "Z2dyaHVqZHVhbGx6bnFz\n" +
            "eHVheXJ2eA==\n" +
            "cXRu\n" +
            "ZG13eW1hcG9teXp6aA==\n" +
            "ZmFuemNrc2FmYWE=\n" +
            "a2NwbQ==\n" +
            "dGZ0amp6Z2RkdmRxYnJxeGs=\n" +
            "aGs=\n" +
            "eWx6\n" +
            "YXd3\n" +
            "emdneHl3eG1ndWJ4\n" +
            "ZW1ncnNkdWp1cXFtZw==\n" +
            "ZWtzbG9naHNocHdvcnJl\n" +
            "a2tkdHB0Y2d5eGk=\n" +
            "cGM=\n" +
            "emJtaW1lcWNmbXZ4ZHVnaQ==\n" +
            "cnBzem1wdnhjaXg=\n" +
            "Y3h1Ynpmb3VwcW1mdWt5Y3A=\n" +
            "dW5h\n" +
            "eWV0d2s=\n" +
            "c2Z0dnhkb2Jpc3F5cXJ4cQ==\n" +
            "ZWR4Yw==\n" +
            "dGZpdmV2\n" +
            "Z3pxbHZndWU=\n" +
            "dHZsbHRx\n" +
            "cHNxbndhaGd5eQ==\n" +
            "dnB0anVqd3Zpa2Fz\n" +
            "Y3dkdXl5YWhy\n" +
            "cWh6cA==\n" +
            "b2VwamhuZ2JodWJuaA==\n" +
            "cGdqenFvaXppdGduZnhqY3Fs\n" +
            "dmNlcGU=\n" +
            "dGFtc3JoZW50c2c=\n" +
            "ZnFkd2xseHFpcmJxbw==\n" +
            "ZnJn\n" +
            "eW91ZGdibWNmb29tZnFheHh2\n" +
            "emZ6cmtsYQ==\n" +
            "eGpsZ2Rpdnpka2M=\n" +
            "dHdmdmFrcXd0YXlxbXl4d3Jj\n" +
            "ZnA=\n" +
            "Y2Q=\n" +
            "ZWtod3VvYWo=\n" +
            "bnlzd2pvenpma3h3YQ==\n" +
            "d29sbXVocm8=\n" +
            "c2d4aGx0bmZhZmE=\n" +
            "YWR5eWhobA==\n" +
            "eWtjZW1zd3FrYWVj\n" +
            "b3V2eXM=\n" +
            "c2ZseHN4d3FkamVyYXE=\n" +
            "ZnhkdG1ta2htd29wZHRieXRqYw==\n" +
            "b21rZ3F4cA==\n" +
            "cnVhc2k=\n" +
            "dmVmbWl1eWRweXo=\n" +
            "WW91IGZvdW5kIGl0ISBUaGFuayB5b3UgZm9yIHlvdXIgaGVscCBhdCBBZHZlbnQgb2YgQ29kZSwgdGhpcyBhbWF6b24gdm91Y2hlciBpcyBhIGxpdHRsZSB0aGFuayB5b3UgZnJvbSBtZSBhbmQgbXkgZmFtaWx5ISBUaGUgc2Vjb25kIHBhcnQgb2YgeW91ciBjb2RlIGlzOiA4MDM3MTYyIC0gdG8gZ2V0IHRoZSBmaXJzdCBwYXJ0IHBsZWFzZSBjb250YWN0IG1lIG9uIERpc2NvcmQgOik=\n" +
            "eWxubHh3eGtvYWZjYmZkc3g=\n" +
            "Ynd4ZWtx\n" +
            "aWtiamt2Y2dl\n" +
            "cWN5Ym1veWV6ZnZ4empyY3N5YQ==\n" +
            "Y2hkZ3ZsZQ==\n" +
            "d3dzbw==\n" +
            "ZWFhZ3V1aHg=\n" +
            "Yml3enBjc2t2YXBidWZ6cw==\n" +
            "bG50aW1wZWN5eWtkcndh\n" +
            "c25rZnZh\n" +
            "dmNlZQ==\n" +
            "YmV6bQ==\n" +
            "ZXl6anp3ZXhwYXF6Y212d3JvZA==\n" +
            "eGtveGE=\n" +
            "cmpmZGV1cA==\n" +
            "cGl6dmZk\n" +
            "enJsa2J3YWs=\n" +
            "eHdhcmhnbGJ5ZGtw\n" +
            "bXpsZ2NlZ2FxbGlpdmFx\n" +
            "YWtqZ25obw==\n" +
            "bm5xZ3JsbnZvdGhjeGp0eA==\n" +
            "aWF0d2h6\n" +
            "ZGNkem16bHA=\n" +
            "a3lyc2VhZWVscmJidw==\n" +
            "ZnNhb3BocWNwbWw=\n" +
            "a2l0amtsY3BuenE=\n" +
            "dG9qcWxxbXl6amlvbA==\n" +
            "dnNld3JldmFzYmJzenZkZA==\n" +
            "emZlcnpzYXp1YmRjdQ==\n" +
            "eWF0cXhybGpl\n" +
            "bWNuYg==\n" +
            "cnhtemNlY3dldnB1eHpt\n" +
            "b3pyam5pZWtp\n" +
            "aXdndWN3Z3B2cGVxZnNt\n" +
            "Y3N5d2ZzdWFxbXlrdGg=\n" +
            "ZXlvcHRkaWo=\n" +
            "cXVrcXprdQ==\n" +
            "aXQ=\n" +
            "Z2RycHlq\n" +
            "amVpag==\n" +
            "bnBxdW1xbm94dGs=\n" +
            "d3dsdw==\n" +
            "eW9vZ3dibA==\n" +
            "enB5cW9sZnRzZGx6Z3N0c2c=\n" +
            "enQ=\n" +
            "b3puY3Bod3Jic21j\n" +
            "YmRlbw==\n" +
            "eWdsd3lhenVub2xla25nZmE=\n" +
            "dW8=\n" +
            "em5qcW5qcnJpZnpvb293dnhq\n" +
            "a3Z2dXlwZ294dm53\n" +
            "bXRmbWlydw==\n" +
            "emJjZnc=\n" +
            "YmVleQ==\n" +
            "ZmFpYmw=\n" +
            "dnd0c2xn\n" +
            "ZmthZQ==\n" +
            "cGN6aW52\n" +
            "Y2x0bm5weW96aXhkZGM=\n" +
            "YW5s\n" +
            "anV5eXE=\n" +
            "bW9zdm1rdg==\n" +
            "eGhpbWZ4bXBrZmN1ZHZmYmp1\n" +
            "a21rdHJlZGNrd2VrZmF1d2hm\n" +
            "dHA=\n" +
            "enpraml6bnB6\n" +
            "Z2x3eg==\n" +
            "cW96dmhieGo=\n" +
            "ZWFham4=\n" +
            "bmFkbWpvdWs=\n" +
            "cmNsd3htaWw=\n" +
            "cmpncmVyYW1qd3FjZQ==\n" +
            "bmlianJx\n" +
            "bGhxY3d4bA==\n" +
            "ZmVrdW50dmVieHVxamNqeHJz\n" +
            "YmliZ2VobG5zZ2lxamJ6a2g=\n" +
            "ZGlyc2JvcG9pbGdndWhs\n" +
            "dmRoa3hnamJhZ3Vhc3Rr\n" +
            "Y3k=\n" +
            "ZXhnendsZ29rY2ZidHVheGw=\n" +
            "YnJ3c3o=\n" +
            "c25qZ3ZtYXE=\n" +
            "YnNwaG1zY3h5ZGNwcnZ2eXM=\n" +
            "a2xscnlkYQ==\n" +
            "Z2N1aGhxd3lmZGU=\n" +
            "dHNhcWtncWQ=\n" +
            "Y3Y=\n" +
            "ZHphdmhraWl1\n" +
            "empwdQ==\n" +
            "a3I=\n" +
            "eXl0eHRmcHRh\n" +
            "ZW9hc3V6\n" +
            "eXphaXdu\n" +
            "aW9hb2NqbnZ6cG92ZHBzYw==\n" +
            "eXluamhueGNobmo=\n" +
            "Ym4=";

    public static void main(String[] args) throws IOException {
        String[] inputs = INPUT.split("\n");

        int line = 0;
        for (String input : inputs) {
            try {
                String s = new String(Base64.getDecoder().decode(input));
                System.out.println(s);
                line = Integer.parseInt(s);
            } catch (NumberFormatException e) {
                //ignored
            }
        }

        System.out.println(new String(Base64.getDecoder().decode(inputs[line])));
    }

}